// @vitest-environment node
//
// Static check that every docs tab has a file where the *deployed* site will look for it — no DOM,
// no browser. The node environment is not optional: under jsdom, `import.meta.url` is an http: URL
// and `fileURLToPath` throws (same reason `demo-markup.test.ts` pins it).
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

/**
 * Guard against the docs viewer shipping tabs whose markdown isn't deployed.
 *
 * `demo/docs.html` fetches each tab from the relative path `./docs/<doc>.md`. Two different things
 * resolve that path:
 *
 *   - locally, `scripts/dev-server.mjs` special-cases `/docs/` onto the repo-level `docs/` folder,
 *     so every tab resolves and every tab looks fine;
 *   - in production, `vercel.json` sets `"outputDirectory": "demo"`, so the web root *is* `demo/`
 *     and the same path resolves to `demo/docs/<doc>.md` — no mapping, no repo-level folder.
 *
 * A real instance of this shipped. `demo/docs/` contained exactly one file, `getting-started.md`,
 * hand-copied in at some point and 700 lines out of date by the time anyone noticed. Catalog and
 * Architecture had no copy at all, so on the live site both tabs fetched a 404 and rendered the
 * page's own fallback string — "Could not load docs/catalog.md (HTTP 404)" — while every local
 * check, including the browser tier, passed. The dev server's convenience mapping is what hid it:
 * the pages were only ever broken where nobody was looking.
 *
 * Nothing caught it. Not the unit tests, which never touch `demo/`; not `demo-markup.test.ts`,
 * which checks tag nesting and does not know a fetch happens; not `test/browser/docs-toc.test.mjs`,
 * which drives the page through that same forgiving dev server. This is the cheap check that
 * would have caught it, and it deliberately asserts against the deploy path rather than the
 * dev-server one — testing the mapping that hid the bug would just reproduce the blind spot.
 */

const ROOT = fileURLToPath(new URL('..', import.meta.url))
const DOCS_HTML = `${ROOT}demo/docs.html`

/**
 * Re-derive the tab list from the page instead of hardcoding it, so a fourth tab is covered the
 * moment it is added — a hardcoded list would silently keep passing while the new tab 404s, which
 * is the exact shape of the bug this file exists to catch.
 */
function docKeysFromPage(html: string): string[] {
  const map = /var DOCS = \{([\s\S]*?)\}/.exec(html)
  expect(map, 'could not find the `var DOCS = {...}` map in demo/docs.html').not.toBeNull()
  const keys = [...map![1].matchAll(/(?:^|,)\s*'?([\w-]+)'?\s*:/g)].map((m) => m[1])
  expect(keys.length, 'the `DOCS` map in demo/docs.html parsed to zero tabs').toBeGreaterThan(0)
  return keys
}

const html = readFileSync(DOCS_HTML, 'utf8')
const DOC_KEYS = docKeysFromPage(html)

describe('demo docs are deployed alongside the page that fetches them', () => {
  it('parses the tab list out of docs.html', () => {
    // Not redundant with the per-key tests below: those are generated *from* this list, so if the
    // regex silently matched the wrong thing they would all pass against a bogus set of names.
    expect(DOC_KEYS).toEqual(expect.arrayContaining(['getting-started', 'catalog', 'design']))
  })

  it.each(DOC_KEYS)('%s.md exists at the path the deployed site fetches', (key) => {
    // `demo/docs/`, not the repo-level `docs/` — see the block comment above.
    expect(
      existsSync(`${ROOT}demo/docs/${key}.md`),
      `demo/docs/${key}.md is missing, so the "${key}" tab 404s in production even though it ` +
        `works locally. Run \`node scripts/sync-demo-docs.mjs\` and commit the result.`
    ).toBe(true)
  })

  it.each(DOC_KEYS)('%s.md matches its source doc', (key) => {
    // The deployed copies are generated by `scripts/sync-demo-docs.mjs`, so drift means someone
    // edited `docs/` without re-running the build — which is how the shipped `getting-started.md`
    // copy ended up 700 lines behind its source while still rendering a plausible-looking page.
    const source = readFileSync(`${ROOT}docs/${key}.md`, 'utf8')
    const deployed = readFileSync(`${ROOT}demo/docs/${key}.md`, 'utf8')
    expect(
      deployed === source,
      `demo/docs/${key}.md has drifted from docs/${key}.md. Run ` +
        `\`node scripts/sync-demo-docs.mjs\` and commit the result.`
    ).toBe(true)
  })

  it('every ?doc= link in the nav points at a real tab', () => {
    // The nav is the other way in. A link to a tab `DOCS` doesn't list silently falls back to
    // Getting Started, so a typo here reads as "Architecture is broken" rather than as a 404.
    const nav = readFileSync(`${ROOT}demo/nav.js`, 'utf8')
    const linked = [...nav.matchAll(/docs\.html\?doc=([\w-]+)/g)].map((m) => m[1])
    expect(linked.length, 'found no ?doc= links in demo/nav.js').toBeGreaterThan(0)
    expect(linked.filter((doc) => !DOC_KEYS.includes(doc))).toEqual([])
  })
})
